- name: pre-cassandra setup
  hosts: all
  become: yes
  tasks:
    - name: install rng-tools
      yum:
        name: rng-tools
        state: present
    - name: start rngd
      systemd:
        name: rngd
        state: started
    - name: Generate /etc/hosts file content
      set_fact:
        etc_hosts_content: |
          {% for host in ansible_play_hosts %}{{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ host }}.novalocal {{ host }}
          {% endfor %}
      run_once: true
    - name: Create entries in /etc/hosts for all nodes
      blockinfile:
        path: /etc/hosts
        create: no
        state: present
        block: "{{ hostvars[ansible_play_hosts[0]].etc_hosts_content }}"

- name: install prerequisites
  hosts: cassandra
  become: yes
  tags:
    - prereq
  tasks:
    - include_role:
        name: ansible-role-ntp
    - include_role:
        name: ansible-role-java

- name: install, configure and start cassandra
  hosts: cassandra
  become: yes
  tags:
    - cassandra
  vars:
      cassandra_cluster_name: my_cluster
      cassandra_keyspaces:
        - my_keyspace1
      java_packages: openjdk-8-jdk
  tasks:
    - include_role:
        name: ansible-cassandra
    